<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>
		@section('title')
			{{ config('app.name', 'Laravel') }} |
		@show
	</title>
	<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'>
	<link href="{{ asset('admin/assets/images/logo.png') }}" rel="icon" type="image/gif" sizes="32x32">
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
	<!-- global css -->
	<link href="{{ asset('admin/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
	<link href="{{ asset('admin/assets/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css"/>
	<link href="{{ asset('admin/assets/css/custom_css/chandra.css') }}" rel="stylesheet" type="text/css"/>
	<link href="{{ asset('admin/assets/css/custom_css/metisMenu.css') }}" rel="stylesheet" type="text/css"/>
	<link href="{{ asset('admin/assets/css/custom_css/panel.css') }}" rel="stylesheet" type="text/css"/>
	<link href="{{ asset('admin/assets/css/custom_css/fixed_layout.css') }}" rel="stylesheet" type="text/css"/>
	<!-- end of global css -->
	<!--page level css-->
@yield('header_styles')
<!--end of page level css-->
</head>
<body class="skin-chandra fixed_menu">
<!-- header logo: style can be found in header-->
<header class="header">
	<nav class="navbar navbar-fixed-top" role="navigation">
		<a href="" class="logo" style="color:white;">
			<h2 style="margin: 10px 0;">
				Onesaway.com
			</h2>
		</a>
		<!-- Header Navbar: style can be found in header-->
		<!-- Sidebar toggle button-->
		<!-- Sidebar toggle button-->
		<div>
			<a href="" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button" style="margin: 10px 0;">
				<i class="fa fa-fw fa-hand-o-left"></i>
			</a>
		</div>
		
		<div class="navbar-right">
			<ul class="nav navbar-nav">
				
				{{-- messages --}}
				@include('admin.layouts._messages')
				
				{{-- tasks --}}
				{{-- @include('admin.layouts._tasks')--}}
				
				{{-- notifications --}}
				{{--@include('admin.layouts._notifications')--}}
				
				{{-- User Account --}}
				@include('admin.layouts._user_menu')
			
			</ul>
		</div>
	</nav>
</header>
<div class="wrapper row-offcanvas row-offcanvas-left">
	<!-- Left side column. contains the logo and sidebar -->
	<aside class="left-side sidebar-offcanvas">
		<!-- sidebar: style can be found in sidebar-->
		<div class="menu_scroll">
			<section class="sidebar ">
				<div id="menu" role="navigation">
					
					{{-- user bio --}}
					@include('admin.layouts._left_bio')
					
					<ul class="navigation">
						{{-- Menus generated by CRUD generator --}}
						@include('admin/layouts/menu')
					</ul>
					<!-- / .navigation -->
				</div>
				<!-- menu -->
			</section>
		</div>
		<!-- /.sidebar -->
	</aside>
	<aside class="right-side right-padding">
		
		<!-- Notifications -->
		
		<!-- Content -->
	@yield('content')
	
	<!-- /.content -->
	</aside>
	<!-- /.right-side -->
</div>
<!-- /.right-side -->
<!-- ./wrapper -->
<!-- global js -->
<script src="{{ asset('admin/assets/js/jquery-1.11.1.min.js') }}" type="text/javascript"></script>
@if (Request::is('admin/draggable_portlets'))
	<script src="{{ asset('admin/assets/js/custom_js/jquery.ui.min.js') }}" type="text/javascript"></script>
@endif
<script src="{{ asset('admin/assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/js/custom_js/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/js/custom_js/metisMenu.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/vendors/jquery-slimscroll/js/jquery.slimscroll.min.js') }}"
        type="text/javascript"></script>
<script src="{{ asset('admin/assets/js/custom_js/rightside_bar.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/js/custom_js/fixed_layout.js') }}" type="text/javascript"></script>
<!-- end of page level js -->
<!-- begin page level js -->
@yield('footer_scripts')

<!-- end page level js -->
</body>
</html>